spring:
  application:
    name: nickcode-back
  # default "dev" environment
  profiles:
    active: dev
  # support swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    # 1 day
    timeout: 86400
  # Database
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/nickcode
    username: root
    password: AQ31km7q5#Hc
  # Files upload manage
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
# Gateway
server:
  address: 0.0.0.0
  port: 8103
  servlet:
    context-path: /api
    # cookie 1 day
    session:
      cookie:
        max-age: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 #  default 1
      logic-not-delete-value: 0 # default 0
# 对象存储
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "nickcode interface"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.becoze.nickcode.controller
# Code Sandbox config
codesandbox:
  codeSandboxName: RemoteCodeSandbox # DemoCodeSandbox, RemoteCodeSandbox, ThirdPartyCodeSandbox